# Generated by Django 4.1.6 on 2023-02-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Servicios', '0003_alter_activo_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='lejago',
            new_name='legajo',
        ),
    ]
